export { hasElementWithoutEdges } from './hasElementWithoutEdges';
export { hasNoInputOrOutput } from './hasNoInputOrOutput';
export { hasIncorrectMOfN } from './hasIncorrectMOfN';
export { isSwitcherSchemeIncorrect } from './isSwitcherSchemeIncorrect';
export { hasSwitcher } from './hasSwitcher';
export { hasNoVertexes } from './hasNoVertexes';
export { isEmptyGraph } from './isEmptyGraph';
export { hasMajority } from './hasMajority';
export { isReserved } from './isReserved';
