const data = {
	graph: [
		{
			value: null,
			geometry: {
				x: 200,
				y: 105,
				width: 70,
				height: 52,
			},
			style: 'rectangle',
			vertex: true,
			edge: false,
			parent: '1',
			id: '2',
			source: null,
			target: null,
			mxObjectId: 'mxCell#7',
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '7',
					edge: true,
					parent: '1',
					source: '4',
					target: '2',
					mxObjectId: 'mxCell#14',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '8',
					edge: true,
					parent: '1',
					source: '2',
					target: '5',
					mxObjectId: 'mxCell#15',
				},
			],
		},
		{
			value: null,
			geometry: {
				x: 20,
				y: 114,
				width: 35,
				height: 35,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
				relative: false,
			},
			style: 'input',
			vertex: true,
			edge: false,
			connectable: true,
			visible: true,
			collapsed: false,
			mxTransient: [
				'id',
				'value',
				'parent',
				'source',
				'target',
				'children',
				'edges',
			],
			parent: '1',
			id: '3',
			source: null,
			target: null,
			mxObjectId: 'mxCell#9',
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '6',
					edge: true,
					parent: '1',
					source: '3',
					target: '4',
					mxObjectId: 'mxCell#13',
				},
			],
		},
		{
			value: null,
			geometry: {
				x: 100,
				y: 105,
				width: 70,
				height: 52,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
				relative: false,
			},
			style: 'rectangle',
			vertex: true,
			edge: false,
			connectable: true,
			visible: true,
			collapsed: false,
			mxTransient: [
				'id',
				'value',
				'parent',
				'source',
				'target',
				'children',
				'edges',
			],
			parent: '1',
			id: '4',
			source: null,
			target: null,
			mxObjectId: 'mxCell#10',
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '6',
					edge: true,
					parent: '1',
					source: '3',
					target: '4',
					mxObjectId: 'mxCell#13',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '7',
					edge: true,
					parent: '1',
					source: '4',
					target: '2',
					mxObjectId: 'mxCell#14',
				},
			],
		},
		{
			value: null,
			geometry: {
				x: 330,
				y: 114,
				width: 35,
				height: 35,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
				relative: false,
			},
			style: 'output',
			vertex: true,
			edge: false,
			connectable: true,
			visible: true,
			collapsed: false,
			mxTransient: [
				'id',
				'value',
				'parent',
				'source',
				'target',
				'children',
				'edges',
			],
			parent: '1',
			id: '5',
			source: null,
			target: null,
			mxObjectId: 'mxCell#12',
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '8',
					edge: true,
					parent: '1',
					source: '2',
					target: '5',
					mxObjectId: 'mxCell#15',
				},
			],
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '6',
			edge: true,
			parent: '1',
			source: '3',
			target: '4',
			mxObjectId: 'mxCell#13',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '7',
			edge: true,
			parent: '1',
			source: '4',
			target: '2',
			mxObjectId: 'mxCell#14',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '8',
			edge: true,
			parent: '1',
			source: '2',
			target: '5',
			mxObjectId: 'mxCell#15',
		},
	],
};

const data1 = {
	graph: [
		{
			value: '2',
			geometry: {
				x: 200,
				y: 105,
				width: 70,
				height: 52,
				relative: false,
			},
			style: 'rectangle',
			id: '2',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '7',
					edge: true,
					parent: '1',
					source: '4',
					target: '2',
					mxObjectId: 'mxCell#7',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '8',
					edge: true,
					parent: '1',
					source: '2',
					target: '5',
					mxObjectId: 'mxCell#8',
				},
			],
			mxObjectId: 'mxCell#6',
		},
		{
			value: null,
			geometry: {
				x: 20,
				y: 114,
				width: 35,
				height: 35,
				relative: false,
			},
			style: 'input',
			id: '3',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '6',
					edge: true,
					parent: '1',
					source: '3',
					target: '4',
					mxObjectId: 'mxCell#10',
				},
			],
			mxObjectId: 'mxCell#9',
		},
		{
			value: '1',
			geometry: {
				x: 100,
				y: 105,
				width: 70,
				height: 52,
				relative: false,
			},
			style: 'rectangle',
			id: '4',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '6',
					edge: true,
					parent: '1',
					source: '3',
					target: '4',
					mxObjectId: 'mxCell#10',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '7',
					edge: true,
					parent: '1',
					source: '4',
					target: '2',
					mxObjectId: 'mxCell#7',
				},
			],
			mxObjectId: 'mxCell#11',
		},
		{
			value: null,
			geometry: {
				x: 330,
				y: 114,
				width: 35,
				height: 35,
				relative: false,
			},
			style: 'output',
			id: '5',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '8',
					edge: true,
					parent: '1',
					source: '2',
					target: '5',
					mxObjectId: 'mxCell#8',
				},
			],
			mxObjectId: 'mxCell#12',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '6',
			edge: true,
			parent: '1',
			source: '3',
			target: '4',
			mxObjectId: 'mxCell#10',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '7',
			edge: true,
			parent: '1',
			source: '4',
			target: '2',
			mxObjectId: 'mxCell#7',
		},
		{
			value: 0.001,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '8',
			edge: true,
			parent: '1',
			source: '2',
			target: '5',
			mxObjectId: 'mxCell#8',
		},
	],
};

const calculate = scheme => {
	const result = [];
	scheme.graph.map(i => (i.value ? result.push(parseFloat(i.value)) : result));
};

calculate(data1);

const d = {
	graph: [
		{
			value: null,
			geometry: { x: 0, y: 29.5, width: 35, height: 35, relative: false },
			style: 'input',
			id: '3',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 47, y: 40.75 },
							{ x: 73, y: 21 },
						],
						offset: null,
					},
					style: null,
					id: '21',
					edge: true,
					parent: '1',
					source: '3',
					target: '5',
					mxObjectId: 'mxCell#41',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 47, y: 53.25 },
							{ x: 73, y: 73 },
						],
						offset: null,
					},
					style: null,
					id: '22',
					edge: true,
					parent: '1',
					source: '3',
					target: '6',
					mxObjectId: 'mxCell#42',
				},
			],
			mxObjectId: 'mxCell#21',
		},
		{
			value: null,
			geometry: {
				x: 85,
				y: 0,
				width: 60,
				height: 42,
				relative: false,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
			},
			style: 'rectangle',
			id: '5',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 157, y: 21 },
							{ x: 183, y: 44.5 },
						],
						offset: null,
					},
					style: null,
					id: '10',
					edge: true,
					parent: '1',
					source: '5',
					target: '9',
					mxObjectId: 'mxCell#29',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 47, y: 40.75 },
							{ x: 73, y: 21 },
						],
						offset: null,
					},
					style: null,
					id: '21',
					edge: true,
					parent: '1',
					source: '3',
					target: '5',
					mxObjectId: 'mxCell#41',
				},
			],
			mxObjectId: 'mxCell#22',
		},
		{
			value: null,
			geometry: {
				x: 85,
				y: 52,
				width: 60,
				height: 42,
				relative: false,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
			},
			style: 'rectangle',
			id: '6',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 157, y: 73 },
							{ x: 183, y: 49.5 },
						],
						offset: null,
					},
					style: null,
					id: '11',
					edge: true,
					parent: '1',
					source: '6',
					target: '9',
					mxObjectId: 'mxCell#30',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 47, y: 53.25 },
							{ x: 73, y: 73 },
						],
						offset: null,
					},
					style: null,
					id: '22',
					edge: true,
					parent: '1',
					source: '3',
					target: '6',
					mxObjectId: 'mxCell#42',
				},
			],
			mxObjectId: 'mxCell#23',
		},
		{
			value: null,
			geometry: {
				x: 195,
				y: 42,
				width: 10,
				height: 10,
				relative: false,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
			},
			style: 'joint',
			id: '9',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 157, y: 21 },
							{ x: 183, y: 44.5 },
						],
						offset: null,
					},
					style: null,
					id: '10',
					edge: true,
					parent: '1',
					source: '5',
					target: '9',
					mxObjectId: 'mxCell#29',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 157, y: 73 },
							{ x: 183, y: 49.5 },
						],
						offset: null,
					},
					style: null,
					id: '11',
					edge: true,
					parent: '1',
					source: '6',
					target: '9',
					mxObjectId: 'mxCell#30',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 217, y: 44.5 },
							{ x: 243, y: 21 },
						],
						offset: null,
					},
					style: null,
					id: '16',
					edge: true,
					parent: '1',
					source: '9',
					target: '14',
					mxObjectId: 'mxCell#35',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 217, y: 49.5 },
							{ x: 243, y: 73 },
						],
						offset: null,
					},
					style: null,
					id: '17',
					edge: true,
					parent: '1',
					source: '9',
					target: '15',
					mxObjectId: 'mxCell#36',
				},
			],
			mxObjectId: 'mxCell#24',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: [
					{ x: 157, y: 21 },
					{ x: 183, y: 44.5 },
				],
				offset: null,
			},
			style: null,
			id: '10',
			edge: true,
			parent: '1',
			source: '5',
			target: '9',
			mxObjectId: 'mxCell#29',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: [
					{ x: 157, y: 73 },
					{ x: 183, y: 49.5 },
				],
				offset: null,
			},
			style: null,
			id: '11',
			edge: true,
			parent: '1',
			source: '6',
			target: '9',
			mxObjectId: 'mxCell#30',
		},
		{
			value: null,
			geometry: {
				x: 255,
				y: 0,
				width: 60,
				height: 42,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
				relative: false,
			},
			style: 'rectangle',
			vertex: true,
			edge: false,
			connectable: true,
			visible: true,
			collapsed: false,
			mxTransient: [
				'id',
				'value',
				'parent',
				'source',
				'target',
				'children',
				'edges',
			],
			parent: '1',
			id: '14',
			source: null,
			target: null,
			mxObjectId: 'mxCell#33',
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 217, y: 44.5 },
							{ x: 243, y: 21 },
						],
						offset: null,
					},
					style: null,
					id: '16',
					edge: true,
					parent: '1',
					source: '9',
					target: '14',
					mxObjectId: 'mxCell#35',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 327, y: 21 },
							{ x: 353, y: 40.75 },
						],
						offset: null,
					},
					style: null,
					id: '19',
					edge: true,
					parent: '1',
					source: '14',
					target: '18',
					mxObjectId: 'mxCell#39',
				},
			],
		},
		{
			value: null,
			geometry: {
				x: 255,
				y: 52,
				width: 60,
				height: 42,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
				relative: false,
			},
			style: 'rectangle',
			vertex: true,
			edge: false,
			connectable: true,
			visible: true,
			collapsed: false,
			mxTransient: [
				'id',
				'value',
				'parent',
				'source',
				'target',
				'children',
				'edges',
			],
			parent: '1',
			id: '15',
			source: null,
			target: null,
			mxObjectId: 'mxCell#34',
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 217, y: 49.5 },
							{ x: 243, y: 73 },
						],
						offset: null,
					},
					style: null,
					id: '17',
					edge: true,
					parent: '1',
					source: '9',
					target: '15',
					mxObjectId: 'mxCell#36',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 327, y: 73 },
							{ x: 353, y: 53.25 },
						],
						offset: null,
					},
					style: null,
					id: '20',
					edge: true,
					parent: '1',
					source: '15',
					target: '18',
					mxObjectId: 'mxCell#40',
				},
			],
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: [
					{ x: 217, y: 44.5 },
					{ x: 243, y: 21 },
				],
				offset: null,
			},
			style: null,
			id: '16',
			edge: true,
			parent: '1',
			source: '9',
			target: '14',
			mxObjectId: 'mxCell#35',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: [
					{ x: 217, y: 49.5 },
					{ x: 243, y: 73 },
				],
				offset: null,
			},
			style: null,
			id: '17',
			edge: true,
			parent: '1',
			source: '9',
			target: '15',
			mxObjectId: 'mxCell#36',
		},
		{
			value: null,
			geometry: {
				x: 365,
				y: 29.5,
				width: 35,
				height: 35,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
				relative: false,
			},
			style: 'output',
			vertex: true,
			edge: false,
			connectable: true,
			visible: true,
			collapsed: false,
			mxTransient: [
				'id',
				'value',
				'parent',
				'source',
				'target',
				'children',
				'edges',
			],
			parent: '1',
			id: '18',
			source: null,
			target: null,
			mxObjectId: 'mxCell#38',
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 327, y: 21 },
							{ x: 353, y: 40.75 },
						],
						offset: null,
					},
					style: null,
					id: '19',
					edge: true,
					parent: '1',
					source: '14',
					target: '18',
					mxObjectId: 'mxCell#39',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
						TRANSLATE_CONTROL_POINTS: true,
						alternateBounds: null,
						sourcePoint: null,
						targetPoint: null,
						points: [
							{ x: 327, y: 73 },
							{ x: 353, y: 53.25 },
						],
						offset: null,
					},
					style: null,
					id: '20',
					edge: true,
					parent: '1',
					source: '15',
					target: '18',
					mxObjectId: 'mxCell#40',
				},
			],
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: [
					{ x: 327, y: 21 },
					{ x: 353, y: 40.75 },
				],
				offset: null,
			},
			style: null,
			id: '19',
			edge: true,
			parent: '1',
			source: '14',
			target: '18',
			mxObjectId: 'mxCell#39',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: [
					{ x: 327, y: 73 },
					{ x: 353, y: 53.25 },
				],
				offset: null,
			},
			style: null,
			id: '20',
			edge: true,
			parent: '1',
			source: '15',
			target: '18',
			mxObjectId: 'mxCell#40',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: [
					{ x: 47, y: 40.75 },
					{ x: 73, y: 21 },
				],
				offset: null,
			},
			style: null,
			id: '21',
			edge: true,
			parent: '1',
			source: '3',
			target: '5',
			mxObjectId: 'mxCell#41',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: [
					{ x: 47, y: 53.25 },
					{ x: 73, y: 73 },
				],
				offset: null,
			},
			style: null,
			id: '22',
			edge: true,
			parent: '1',
			source: '3',
			target: '6',
			mxObjectId: 'mxCell#42',
		},
	],
};
