const data = {
	graph: [
		{
			value: null,
			geometry: {
				x: 200,
				y: 105,
				width: 70,
				height: 52,
			},
			style: 'rectangle',
			vertex: true,
			edge: false,
			parent: '1',
			id: '2',
			source: null,
			target: null,
			mxObjectId: 'mxCell#7',
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '7',
					edge: true,
					parent: '1',
					source: '4',
					target: '2',
					mxObjectId: 'mxCell#14',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '8',
					edge: true,
					parent: '1',
					source: '2',
					target: '5',
					mxObjectId: 'mxCell#15',
				},
			],
		},
		{
			value: null,
			geometry: {
				x: 20,
				y: 114,
				width: 35,
				height: 35,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
				relative: false,
			},
			style: 'input',
			vertex: true,
			edge: false,
			connectable: true,
			visible: true,
			collapsed: false,
			mxTransient: [
				'id',
				'value',
				'parent',
				'source',
				'target',
				'children',
				'edges',
			],
			parent: '1',
			id: '3',
			source: null,
			target: null,
			mxObjectId: 'mxCell#9',
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '6',
					edge: true,
					parent: '1',
					source: '3',
					target: '4',
					mxObjectId: 'mxCell#13',
				},
			],
		},
		{
			value: null,
			geometry: {
				x: 100,
				y: 105,
				width: 70,
				height: 52,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
				relative: false,
			},
			style: 'rectangle',
			vertex: true,
			edge: false,
			connectable: true,
			visible: true,
			collapsed: false,
			mxTransient: [
				'id',
				'value',
				'parent',
				'source',
				'target',
				'children',
				'edges',
			],
			parent: '1',
			id: '4',
			source: null,
			target: null,
			mxObjectId: 'mxCell#10',
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '6',
					edge: true,
					parent: '1',
					source: '3',
					target: '4',
					mxObjectId: 'mxCell#13',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '7',
					edge: true,
					parent: '1',
					source: '4',
					target: '2',
					mxObjectId: 'mxCell#14',
				},
			],
		},
		{
			value: null,
			geometry: {
				x: 330,
				y: 114,
				width: 35,
				height: 35,
				TRANSLATE_CONTROL_POINTS: true,
				alternateBounds: null,
				sourcePoint: null,
				targetPoint: null,
				points: null,
				offset: null,
				relative: false,
			},
			style: 'output',
			vertex: true,
			edge: false,
			connectable: true,
			visible: true,
			collapsed: false,
			mxTransient: [
				'id',
				'value',
				'parent',
				'source',
				'target',
				'children',
				'edges',
			],
			parent: '1',
			id: '5',
			source: null,
			target: null,
			mxObjectId: 'mxCell#12',
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '8',
					edge: true,
					parent: '1',
					source: '2',
					target: '5',
					mxObjectId: 'mxCell#15',
				},
			],
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '6',
			edge: true,
			parent: '1',
			source: '3',
			target: '4',
			mxObjectId: 'mxCell#13',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '7',
			edge: true,
			parent: '1',
			source: '4',
			target: '2',
			mxObjectId: 'mxCell#14',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '8',
			edge: true,
			parent: '1',
			source: '2',
			target: '5',
			mxObjectId: 'mxCell#15',
		},
	],
};

const data1 = {
	graph: [
		{
			value: '2',
			geometry: {
				x: 200,
				y: 105,
				width: 70,
				height: 52,
				relative: false,
			},
			style: 'rectangle',
			id: '2',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '7',
					edge: true,
					parent: '1',
					source: '4',
					target: '2',
					mxObjectId: 'mxCell#7',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '8',
					edge: true,
					parent: '1',
					source: '2',
					target: '5',
					mxObjectId: 'mxCell#8',
				},
			],
			mxObjectId: 'mxCell#6',
		},
		{
			value: null,
			geometry: {
				x: 20,
				y: 114,
				width: 35,
				height: 35,
				relative: false,
			},
			style: 'input',
			id: '3',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '6',
					edge: true,
					parent: '1',
					source: '3',
					target: '4',
					mxObjectId: 'mxCell#10',
				},
			],
			mxObjectId: 'mxCell#9',
		},
		{
			value: '1',
			geometry: {
				x: 100,
				y: 105,
				width: 70,
				height: 52,
				relative: false,
			},
			style: 'rectangle',
			id: '4',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '6',
					edge: true,
					parent: '1',
					source: '3',
					target: '4',
					mxObjectId: 'mxCell#10',
				},
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '7',
					edge: true,
					parent: '1',
					source: '4',
					target: '2',
					mxObjectId: 'mxCell#7',
				},
			],
			mxObjectId: 'mxCell#11',
		},
		{
			value: null,
			geometry: {
				x: 330,
				y: 114,
				width: 35,
				height: 35,
				relative: false,
			},
			style: 'output',
			id: '5',
			vertex: true,
			connectable: true,
			parent: '1',
			source: null,
			target: null,
			edges: [
				{
					value: null,
					geometry: {
						x: 0,
						y: 0,
						width: 0,
						height: 0,
						relative: true,
					},
					style: null,
					id: '8',
					edge: true,
					parent: '1',
					source: '2',
					target: '5',
					mxObjectId: 'mxCell#8',
				},
			],
			mxObjectId: 'mxCell#12',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '6',
			edge: true,
			parent: '1',
			source: '3',
			target: '4',
			mxObjectId: 'mxCell#10',
		},
		{
			value: null,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '7',
			edge: true,
			parent: '1',
			source: '4',
			target: '2',
			mxObjectId: 'mxCell#7',
		},
		{
			value: 0.001,
			geometry: {
				x: 0,
				y: 0,
				width: 0,
				height: 0,
				relative: true,
			},
			style: null,
			id: '8',
			edge: true,
			parent: '1',
			source: '2',
			target: '5',
			mxObjectId: 'mxCell#8',
		},
	],
};

const calculate = scheme => {
	const result = [];
	scheme.graph.map(i => (i.value ? result.push(parseFloat(i.value)) : result));
	console.log('res', result);
};

calculate(data1);
